### ISSUE TITLE
Set up and use browserstack

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-rem-v3#28]
Will address
https://travis-ci.org/urbanriskmap/cognicity-rem/builds/207609977

**Comment by tomasholderness** [comment]
@abrahamq - one to discuss next week; how we extend the Browserstack testing across to the REM.

**Comment by abrahamq** [comment]
For sure, I can do it Monday?

**Comment by abrahamq** [comment]
@matthewberryman Hi Matthew, could I have write access to make a branch and push this stuff up? Looks like the current tests are failing because auth0Lock is being brought in from a CDN: 
`Chrome 56.0.2924 (Mac OS X 10.10.5) the app says hello FAILED
        ReferenceError: Auth0Lock is not defined
            at new App (/Users/abrahamq/Documents/urop/cognicity-rem/scripts/app-bundle.js:214:23)
            at Object.<anonymous> (/Users/abrahamq/Documents/urop/cognicity-rem/test/unit/app.spec.js:6:14)`
I think we'll have to bundle it?

**Comment by tomasholderness** [comment]
@abrahamq I've added both you and @matthewberryman to the REM GitHub team.

**Comment by abrahamq** [comment]
Thanks!

**Comment by abrahamq** [comment]
looks like the team doesn't have write access to this repo? sorry for the bother! 
![screen shot 2017-03-05 at 2 37 21 pm](https://cloud.githubusercontent.com/assets/8716123/23590614/4a812fa0-01b1-11e7-95ac-bc28ee991d1e.png)

**Comment by matthewberryman** [comment]
@abrahamq I have given that team rw permissions for dev and r permission for master.

**Comment by abrahamq** [comment]
browserstack is set up on pr 29: https://github.com/urbanriskmap/cognicity-rem/pull/29 
opening another issue for the auth0-lock issue.

**Comment by tomasholderness** [comment]
Thanks @matthewberryman - I wonder if it lost permissions because of the name change?

**Comment by matthewberryman** [comment]
Shouldn't have. I don't think we set it up as we've not had other people working on it until now. I will check cognicity-server just in case it was a name change.

**Comment by ojha-url** [comment]
@matthewberryman Any updates on this?? Pushed to REM for the first time and getting build fail msgs... Also since there are no tests yet on REM, @abrahamq ?

**Comment by tomasholderness** [comment]
@ojha-url - it still builds in Jenkins right? Its just the Travis tests that are failing?

**Comment by matthewberryman** [comment]
Yes building in jenkins, but failing in travis per https://travis-ci.org/urbanriskmap/cognicity-rem

**Comment by abrahamq** [comment]
Removed testing, fixed by commit d22d6a281da2df01afaf486bd0f01a64d48505ed
