### ISSUE TITLE
need to bundle auth0-lock to support testing

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-rem-v3#30]
Currently auth0-lock is being brought in with a script tag on index.html, but this means that karma can't bring it in during testing, failing with: 

```Chrome 56.0.2924 (Mac OS X 10.10.5) the app says hello FAILED ReferenceError: Auth0Lock is not defined at new App (/Users/abrahamq/Documents/urop/cognicity-rem/scripts/app-bundle.js:214:23) at Object.<anonymous> (/Users/abrahamq/Documents/urop/cognicity-rem/test/unit/app.spec.js:6:14)```

I think the solution is to bundle auth0-lock with our app. There's an npm module https://www.npmjs.com/package/auth0-lock, but I couldn't get it to work? There's no dist/ or build folder in the npm module and the docs seem to point at having to build the module but npm install fails.

**Comment by tomasholderness** [comment]
Because Aurelia, proposed solution would be to extend build script to https://www.npmjs.com/package/gulp-download to get Auth0 lock file from CDN and put somewhere sensible for inclusion in build.
